name: dynamic_form_app
description: "A new Flutter project."
publish_to: "Nicolas Pereira"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  connectivity_plus: ^6.1.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  get: ^4.7.2
  http: ^1.3.0
  shared_preferences: ^2.5.2
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/bg.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_launcher_round.png"
  min_sdk_version: 21
  adaptive_icon_background: "#FFDC2E"
  adaptive_icon_foreground: "assets/icons/ic_launcher_round.png"
